### ISSUE TITLE
Add VLAN protocol, VRRP and adding documentation

### ISSUE THREAD

**Issue by EasyNetDev** [ifupdown-ng/ifupdown-ng#185]
Hi, 

I'm working for a pull request for the following features:

- [x] VLAN protocol 802.1ad and the default 802.1Q support (which is already implemented). Is used where you want to carry Q-in-Q traffic. #191
- [x] Prepare ifupdown-ng for VRRP. #268  
- [x] VRRP executor for Linux, using MACVLAN interface to be used with FRRouting. #272 
- [x] Adding info for VLAN protocol in interfaces-vlan.scd . #191
- [x] Adding documentation for VRRP under interfaces-vrrp.scd .  #272
- [ ] Adding missing interfaces-mpls.scd documentation.

I'm testing VRRP script now to see if is working properly on different setups and I will do a pull request.

Also I'm working mstpd daemon implementation for bridges. In my setups I need to run RSTP, not just standard STP from Linux bridge.

Updates regarding VRRP executor:

- [x] VRRP creates 2 MACVLAN subinterfaces and set protodown on.
- [x] Each MACVLAN interface is named vrrpV-XX-YY, where V is IP protocol number 4 or 6, XX is the main interface index and YY is the VRID. 
- [x] Simple configuration option `vrrp VRID IP1 IP2 ..`

**Comment by EasyNetDev** [comment]
Hi all,

VRRP documentation is submitted with my latest version of VRRP 1.3.

**Comment by Neustradamus** [comment]
To follow

**Comment by Neustradamus** [comment]
VRRP:
- https://github.com/ifupdown-ng/ifupdown-ng/pull/206
- https://github.com/ifupdown-ng/ifupdown-ng/pull/222
- https://github.com/ifupdown-ng/ifupdown-ng/pull/223
- https://github.com/ifupdown-ng/ifupdown-ng/pull/232
- https://github.com/ifupdown-ng/ifupdown-ng/pull/233

**Comment by Neustradamus** [comment]
VLAN protocol + documentation:
- https://github.com/ifupdown-ng/ifupdown-ng/pull/191
